### ISSUE TITLE
Differenza decessi "errata" come dato float

### ISSUE THREAD

**Issue by AndreaGemmani** [ioconto/covid19#3]
Buonasera, volevo farvi presente che quando si esegue una differenza utilizzando Javascript fra due dati di cui almeno uno float (con virgola mobile) il calcolo risultante può rivelarsi sbagliato, o meglio può avere un discostamento dal risultato reale di di circa 10^-14 
A me è capitato di riscontrare il problema nei decessi di Rimini la cui differenza è stimata a 24.799999999999997 invece che 24.8

Per risolvere dovrebbe bastare aggiungere un `number.toFixed(2)` al calcolo di deltaDeaths in processing/index

Si veda questo esempio
https://stackoverflow.com/questions/6027937/javascript-float-subtract

**Comment by ioconto** [comment]
Grazie, stiamo riorganizzando il codice e sicuramente terremo conto del suggerimento
